/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itla.apppatologia.vista.componentes;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import org.itla.apppatologia.vista.MainFrame;
import org.itla.apppatologia.vista.mantenimientos.IMantenimiento;
import org.itla.apppatologia.vista.mantenimientos.PanelEstudio;
import org.itla.apppatologia.vista.mantenimientos.PanelResultado;
import org.itla.apppatologia.vista.viewers.IViewerObservable;
import org.itla.apppatologia.vista.viewers.ViewerEstudio;
import org.itla.apppatologia.vista.viewers.ViewerResultado;

/**
 *
 * @author Chu
 */
public class PanelSubMenuResultado extends javax.swing.JPanel implements ISubMenuObservable{

    JPanel pnForm;
    JPanel pnViewer;
    private ArrayList<IPanelCentralObservador> observadores;
    private IPanelCentralObservador observador;
    private String nombre;
    
    /**
     * Creates new form PanelResultado
     */
    public PanelSubMenuResultado() {
        initComponents();
        pnForm = null;
        pnViewer = null;
        observadores = new ArrayList<>();
        nombre = "estudio";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnSubMenuEstudio = new javax.swing.JPanel();
        tbMenuEstudio = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jPanel9 = new javax.swing.JPanel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jPanel10 = new javax.swing.JPanel();
        jToggleButton7 = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridLayout(0, 1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        pnSubMenuEstudio.setBackground(new java.awt.Color(240, 240, 240));
        pnSubMenuEstudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnSubMenuEstudioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnSubMenuEstudioMouseEntered(evt);
            }
        });
        pnSubMenuEstudio.setLayout(new javax.swing.OverlayLayout(pnSubMenuEstudio));

        tbMenuEstudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        tbMenuEstudio.setText("<html>Estudio</html>");
        tbMenuEstudio.setContentAreaFilled(false);
        tbMenuEstudio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbMenuEstudio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbMenuEstudio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbMenuEstudio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbMenuEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbMenuEstudioActionPerformed(evt);
            }
        });
        pnSubMenuEstudio.add(tbMenuEstudio);

        jPanel1.add(pnSubMenuEstudio);

        jPanel8.setBackground(new java.awt.Color(240, 240, 240));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new javax.swing.OverlayLayout(jPanel8));

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        jToggleButton5.setText("<html>Tipo Estudio</html>");
        jToggleButton5.setContentAreaFilled(false);
        jToggleButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jToggleButton5);

        jPanel1.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(240, 240, 240));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(new javax.swing.OverlayLayout(jPanel9));

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        jToggleButton6.setText("<html>Acción Estudio</html>");
        jToggleButton6.setContentAreaFilled(false);
        jToggleButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jToggleButton6);

        jPanel1.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(240, 240, 240));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(new javax.swing.OverlayLayout(jPanel10));

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        jToggleButton7.setText("<html>Resultado</html>");
        jToggleButton7.setContentAreaFilled(false);
        jToggleButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel10.add(jToggleButton7);

        jPanel1.add(jPanel10);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void tbMenuEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbMenuEstudioActionPerformed
        
        UnSelectAllButton();
        
        tbMenuEstudio.setSelected(true);
        pnSubMenuEstudio.setBackground(new Color(204,204,204));
        
        pnForm = new PanelEstudio();
        MainFrame padre = (MainFrame)observador;
        
        pnViewer = new ViewerEstudio(padre.getEntityManager());
        GetPanel(pnForm, pnViewer, false);
        
        IMantenimiento m = (IMantenimiento)pnForm;
        IViewerObservable v = (IViewerObservable)pnViewer;
        
        m.bind(v, observador);
        v.bind(m);
        
        
        observador.OcultarSubMenu();
        revalidate();
        repaint();
    
    }//GEN-LAST:event_tbMenuEstudioActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        JToggleButton jtb = new JToggleButton();
        for(Component c: jPanel1.getComponents()){
            if (c instanceof JPanel) {
                JPanel jp = new JPanel();
                jp = (JPanel)c;
                jp.setBackground(new Color(240,240,240));
                for(Component cc:jp.getComponents()){
                    if (cc instanceof JToggleButton) {
                        jtb = (JToggleButton)cc;
                        jtb.setSelected(false);
                    }
                }
            }
        }
        jToggleButton5.setSelected(true);
        jPanel8.setBackground(new Color(204,204,204));
        
        
        observador.OcultarSubMenu();
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        JToggleButton jtb = new JToggleButton();
        for(Component c: jPanel1.getComponents()){
            if (c instanceof JPanel) {
                JPanel jp = new JPanel();
                jp = (JPanel)c;
                jp.setBackground(new Color(240,240,240));
                for(Component cc:jp.getComponents()){
                    if (cc instanceof JToggleButton) {
                        jtb = (JToggleButton)cc;
                        jtb.setSelected(false);
                    }
                }
            }
        }
        jToggleButton6.setSelected(true);
        jPanel9.setBackground(new Color(204,204,204));
        
        
        observador.OcultarSubMenu();
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        JToggleButton jtb = new JToggleButton();
        for(Component c: jPanel1.getComponents()){
            if (c instanceof JPanel) {
                JPanel jp = new JPanel();
                jp = (JPanel)c;
                jp.setBackground(new Color(240,240,240));
                for(Component cc:jp.getComponents()){
                    if (cc instanceof JToggleButton) {
                        jtb = (JToggleButton)cc;
                        jtb.setSelected(false);
                    }
                }
            }
        }
        jToggleButton7.setSelected(true);
        jPanel10.setBackground(new Color(204,204,204));
        
        
        observador.OcultarSubMenu();
        
        pnForm = new PanelResultado();
        MainFrame padre = (MainFrame)observador;
        
        pnViewer = new ViewerResultado(padre.getEntityManager());
        GetPanel(pnForm, pnViewer, false);
        
        IMantenimiento m = (IMantenimiento)pnForm;
        IViewerObservable v = (IViewerObservable)pnViewer;
        
        m.bind(v, observador);
        v.bind(m);
        
        revalidate();
        repaint();
        
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void pnSubMenuEstudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSubMenuEstudioMouseClicked
        tbMenuEstudioActionPerformed(null);
    }//GEN-LAST:event_pnSubMenuEstudioMouseClicked

    private void pnSubMenuEstudioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSubMenuEstudioMouseEntered
        
        
    }//GEN-LAST:event_pnSubMenuEstudioMouseEntered

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        jToggleButton5ActionPerformed(null);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        jToggleButton6ActionPerformed(null);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        jToggleButton7ActionPerformed(null);
    }//GEN-LAST:event_jPanel10MouseClicked
    public void UnSelectAllButton(){
        JToggleButton jtb = new JToggleButton();
        for(Component c: jPanel1.getComponents()){
            if (c instanceof JPanel) {
                JPanel jp = new JPanel();
                jp = (JPanel)c;
                jp.setBackground(new Color(240,240,240));
                for(Component cc:jp.getComponents()){
                    if (cc instanceof JToggleButton) {
                        jtb = (JToggleButton)cc;
                        jtb.setSelected(false);
                    }
                }
            }
        }
    }
    public void Enlazar(IPanelCentralObservador o){
        observadores.add(o);
        observador = o;
    }
    @Override
    public void Notificar() {
        for(IPanelCentralObservador ob: observadores){
            //ob.SetPanel(pnForm);
        }
    }

  

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    @Override
    public String getName() {
        return nombre;
    }

    @Override
    public void setName(String name) {
        super.setName(nombre); //To change body of generated methods, choose Tools | Templates.
    }
    

    @Override
    public void GetPanel(JPanel pnfrm,JPanel pnvwr, boolean sobreponer) {
        for(IPanelCentralObservador ob: observadores){
            ob.SetPanel(pnfrm,pnvwr,sobreponer);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JPanel pnSubMenuEstudio;
    private javax.swing.JToggleButton tbMenuEstudio;
    // End of variables declaration//GEN-END:variables
}
