/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itla.apppatologia.vista.componentes;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author Chu
 */
public class PanelSubMenuMedico extends javax.swing.JPanel implements ISubMenuObservable{

    JPanel pnForm;
    JPanel pnViewer;
    private ArrayList<IPanelCentralObservador> observadores;
    private IPanelCentralObservador observador;
    private String nombre;
    /**
     * Creates new form PanelResultado
     */
    public PanelSubMenuMedico() {
        initComponents();
        pnForm = null;
        pnViewer = null;
        observadores = new ArrayList<>();
        nombre = "medico";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jPanel9 = new javax.swing.JPanel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jToggleButton9 = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridLayout(0, 1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        jToggleButton2.setText("<html>Médico</html>");
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton2);

        jPanel1.add(jPanel2);

        jPanel8.setBackground(new java.awt.Color(240, 240, 240));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new javax.swing.OverlayLayout(jPanel8));

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        jToggleButton5.setText("<html>Especialidad</html>");
        jToggleButton5.setContentAreaFilled(false);
        jToggleButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jToggleButton5);

        jPanel1.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(240, 240, 240));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(new javax.swing.OverlayLayout(jPanel9));

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        jToggleButton6.setText("<html>Centro Médico</html>");
        jToggleButton6.setContentAreaFilled(false);
        jToggleButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jToggleButton6);

        jPanel1.add(jPanel9);

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });
        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        jToggleButton9.setContentAreaFilled(false);
        jToggleButton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton9);

        jPanel1.add(jPanel4);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        JToggleButton jtb = new JToggleButton();
        for(Component c: jPanel1.getComponents()){
            if (c instanceof JPanel) {
                JPanel jp = new JPanel();
                jp = (JPanel)c;
                jp.setBackground(new Color(240,240,240));
                for(Component cc:jp.getComponents()){
                    if (cc instanceof JToggleButton) {
                        jtb = (JToggleButton)cc;
                        jtb.setSelected(false);
                    }
                }
            }
        }
        jToggleButton2.setSelected(true);
        jPanel2.setBackground(new Color(204,204,204));
        
        
        observador.OcultarSubMenu();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        JToggleButton jtb = new JToggleButton();
        for(Component c: jPanel1.getComponents()){
            if (c instanceof JPanel) {
                JPanel jp = new JPanel();
                jp = (JPanel)c;
                jp.setBackground(new Color(240,240,240));
                for(Component cc:jp.getComponents()){
                    if (cc instanceof JToggleButton) {
                        jtb = (JToggleButton)cc;
                        jtb.setSelected(false);
                    }
                }
            }
        }
        jToggleButton5.setSelected(true);
        jPanel8.setBackground(new Color(204,204,204));
        
        
        observador.OcultarSubMenu();
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        JToggleButton jtb = new JToggleButton();
        for(Component c: jPanel1.getComponents()){
            if (c instanceof JPanel) {
                JPanel jp = new JPanel();
                jp = (JPanel)c;
                jp.setBackground(new Color(240,240,240));
                for(Component cc:jp.getComponents()){
                    if (cc instanceof JToggleButton) {
                        jtb = (JToggleButton)cc;
                        jtb.setSelected(false);
                    }
                }
            }
        }
        jToggleButton6.setSelected(true);
        jPanel9.setBackground(new Color(204,204,204));
        
        
        observador.OcultarSubMenu();
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        jToggleButton2ActionPerformed(null);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        
        
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        JToggleButton jtb = new JToggleButton();
        for(Component c: jPanel1.getComponents()){
            if (c instanceof JPanel) {
                JPanel jp = new JPanel();
                jp = (JPanel)c;
                jp.setBackground(new Color(240,240,240));
                for(Component cc:jp.getComponents()){
                    if (cc instanceof JToggleButton) {
                        jtb = (JToggleButton)cc;
                        jtb.setSelected(false);
                    }
                }
            }
        }
        jToggleButton9.setSelected(true);
        jPanel4.setBackground(new Color(204,204,204));
        
        
        observador.OcultarSubMenu();
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        jToggleButton9ActionPerformed(null);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        jToggleButton5ActionPerformed(null);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        jToggleButton6ActionPerformed(null);
    }//GEN-LAST:event_jPanel9MouseClicked

    
    @Override
    public void Notificar() {
        for(IPanelCentralObservador ob: observadores){
            //ob.SetPanel(pnForm);
        }
    }

  

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    @Override
    public String getName() {
        return nombre;
    }

    @Override
    public void setName(String name) {
        super.setName(nombre); //To change body of generated methods, choose Tools | Templates.
    }
    

    public void Enlazar(IPanelCentralObservador o){
        observadores.add(o);
        observador = o;
    }
    @Override
    public void GetPanel(JPanel pnfrm,JPanel pnvwr, boolean sobreponer) {
        for(IPanelCentralObservador ob: observadores){
            ob.SetPanel(pnfrm,pnvwr,sobreponer);
        }
    }
    public void UnSelectAllButton(){
        JToggleButton jtb = new JToggleButton();
        for(Component c: jPanel1.getComponents()){
            if (c instanceof JPanel) {
                JPanel jp = new JPanel();
                jp = (JPanel)c;
                jp.setBackground(new Color(240,240,240));
                for(Component cc:jp.getComponents()){
                    if (cc instanceof JToggleButton) {
                        jtb = (JToggleButton)cc;
                        jtb.setSelected(false);
                    }
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
