/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itla.apppatologia.vista.componentes;

import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JPanel;
import org.itla.apppatologia.Repository.Caso;
import org.itla.apppatologia.Repository.Estudio;
import org.itla.apppatologia.Repository.Fragmento;
import org.itla.apppatologia.Repository.Resultado;
import org.itla.apppatologia.vista.mantenimientos.IMantenimiento;
import org.itla.apppatologia.vista.mantenimientos.PanelEstudio;
import org.itla.apppatologia.vista.mantenimientos.PanelFragmento;
import org.itla.apppatologia.vista.mantenimientos.PanelResultado;
import org.itla.apppatologia.vista.viewers.ViewerEstudio;
import org.itla.apppatologia.vista.viewers.ViewerFragmento;
import org.itla.apppatologia.vista.viewers.ViewerResultado;

/**
 *
 * @author Giame
 */
public class PanelCasoPaciente extends javax.swing.JPanel {

    Caso caso;
    Fragmento fragmento = null;
    Resultado resultado = null;
    Estudio estudio = null;
    EntityManager entityManager;
    IMantenimiento mantenimiento;
    public PanelCasoPaciente() {
        initComponents();
    }
    public PanelCasoPaciente(Caso _caso) {
        caso = _caso;
        initComponents();
        PutData();
    }

    public PanelCasoPaciente(Caso _caso, EntityManager em, IMantenimiento mant) {
        caso = _caso;
        entityManager = em;
        mantenimiento = mant;
        initComponents();
        InitEntities();
        initButtoms();
        PutData();
    }
    public void PutData(){
        lblValorCodigo.setText(caso.getIdcaso().toString());
        jLabel9.setText(caso.getNumeroReclamacion());
        jLabel8.setText(caso.getNumeroPoliza());
        jLabel10.setText(caso.getIdaseguradoraAseguradora().getNombre());
        jLabel11.setText(Float.toString(caso.getPorciento_cobertura()));
    }
    public void InitEntities(){
        
        fragmento = entityManager.find(Fragmento.class, caso.getIdfragmento());
        List<Estudio> estudios = entityManager.createNamedQuery("Estudio.findAll").getResultList();
        if(fragmento!=null){
            for (Estudio estudio : estudios) {
            if(estudio.getIdfragmentoFragmento().getIdfragmento()==fragmento.getIdfragmento()){
                this.estudio=estudio;
                }
            }
            try{
                resultado = estudio.getResultado();
            }catch(NullPointerException e){

            }
        }
        
            
    }
    public void initButtoms(){
        if(fragmento==null){
            btnFragmento.setEnabled(false);
            imgFragmento.setEnabled(false);
        }
        if(estudio==null){
            btnEstudio.setEnabled(false);
            imgEstudio.setEnabled(false);
        }
        if(resultado==null){
            btnResultado.setEnabled(false);
            imgResultado.setEnabled(false);
        }
        if(resultado!=null){
            jLabel6.setText("True");
        }
    }
    public void updateButtoms(){
        InitEntities();
        initButtoms();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblValorCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        imgFragmento = new javax.swing.JLabel();
        btnFragmento = new javax.swing.JButton();
        ingPatologo = new javax.swing.JLabel();
        btnPatologo = new javax.swing.JButton();
        imgEstudio = new javax.swing.JLabel();
        btnEstudio = new javax.swing.JButton();
        imgResultado = new javax.swing.JLabel();
        btnResultado = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        jPanel3.setBackground(new java.awt.Color(255, 251, 251));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255)));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Caso #");

        lblValorCodigo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblValorCodigo.setText("0");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setText("No. reclamación");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setText("No. póliza");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setText("Aseguradora");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setText("Porciento cobertura");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/principales/historial-medico.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel11.setText("jLabel11");

        jPanel2.setBackground(new java.awt.Color(255, 251, 251));

        jPanel1.setBackground(new java.awt.Color(255, 251, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgFragmento.setBackground(new java.awt.Color(255, 204, 204));
        imgFragmento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imgFragmento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/botones/radiacion (1).png"))); // NOI18N
        imgFragmento.setToolTipText("Ver fragmento relacionado al caso.");
        imgFragmento.setBorder(null);
        imgFragmento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgFragmento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgFragmentoMouseClicked(evt);
            }
        });
        jPanel1.add(imgFragmento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 40));

        btnFragmento.setBackground(new java.awt.Color(255, 235, 255));
        btnFragmento.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnFragmento.setText("Fragmento");
        btnFragmento.setToolTipText("Ver fragmento relacionado al caso.");
        btnFragmento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFragmento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFragmentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFragmento, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, -1, 20));

        ingPatologo.setBackground(new java.awt.Color(255, 204, 204));
        ingPatologo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ingPatologo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/botones/cientifico.png"))); // NOI18N
        ingPatologo.setToolTipText("Ver Pátologo encargado del caso.");
        ingPatologo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ingPatologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 40, 40));

        btnPatologo.setBackground(new java.awt.Color(255, 235, 255));
        btnPatologo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnPatologo.setText("Patólogo");
        btnPatologo.setToolTipText("Ver Pátologo encargado del caso.");
        btnPatologo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnPatologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 20));

        imgEstudio.setBackground(new java.awt.Color(255, 204, 204));
        imgEstudio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imgEstudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/botones/biologia (1).png"))); // NOI18N
        imgEstudio.setToolTipText("Ver el estudio del Fragmento.");
        imgEstudio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgEstudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgEstudioMouseClicked(evt);
            }
        });
        jPanel1.add(imgEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 40, 40));

        btnEstudio.setBackground(new java.awt.Color(255, 235, 255));
        btnEstudio.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnEstudio.setText("Estudio");
        btnEstudio.setToolTipText("Ver el estudio del Fragmento.");
        btnEstudio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudioActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 80, 20));

        imgResultado.setBackground(new java.awt.Color(255, 204, 204));
        imgResultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imgResultado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/botones/analitica_2.png"))); // NOI18N
        imgResultado.setToolTipText("Ver Resultado del Estudio.");
        imgResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgResultadoMouseClicked(evt);
            }
        });
        jPanel1.add(imgResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 40));

        btnResultado.setBackground(new java.awt.Color(255, 235, 255));
        btnResultado.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnResultado.setText("Resultado");
        btnResultado.setToolTipText("Ver Resultado del Estudio.");
        btnResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 100, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblValorCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFragmentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFragmentoActionPerformed
       
        verFragmentoDePaciente();
    }//GEN-LAST:event_btnFragmentoActionPerformed

    private void imgFragmentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFragmentoMouseClicked
        verFragmentoDePaciente();
    }//GEN-LAST:event_imgFragmentoMouseClicked

    private void btnEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudioActionPerformed
        verEstudioDePaciente();
    }//GEN-LAST:event_btnEstudioActionPerformed

    private void imgEstudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgEstudioMouseClicked
        verEstudioDePaciente();
    }//GEN-LAST:event_imgEstudioMouseClicked

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        verReSultadoDePaciente();
    }//GEN-LAST:event_btnResultadoActionPerformed

    private void imgResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgResultadoMouseClicked
        verReSultadoDePaciente();
    }//GEN-LAST:event_imgResultadoMouseClicked

    public void verFragmentoDePaciente(){
        JPanel pnFrm = new PanelFragmento();
        JPanel pnView = new ViewerFragmento(entityManager);
        mantenimiento.CargarMantenimiento(pnView, pnFrm, true);
        mantenimiento.MandarSizePadre(0);      
        
        Fragmento frag = entityManager.find(Fragmento.class, caso.getIdfragmento());
        ((ViewerFragmento)pnView).setFragmentoSelected(frag);
        
    }

    public void verEstudioDePaciente(){
        JPanel pnFrm = new PanelEstudio();
        JPanel pnView = new ViewerEstudio(entityManager);
        mantenimiento.CargarMantenimiento(pnView, pnFrm, true);
        mantenimiento.MandarSizePadre(0);   
        
        Fragmento frag = entityManager.find(Fragmento.class, caso.getIdfragmento());
        List<Estudio> estudios = entityManager.createNamedQuery("Estudio.findAll").getResultList();
        Estudio est = null;
        for (Estudio estudio : estudios) {
            if(estudio.getIdfragmentoFragmento().getIdfragmento()==frag.getIdfragmento()){
                est=estudio;
            }
        }
        ((ViewerEstudio)pnView).setEstudioSelected(est);
        
    }
    public void verReSultadoDePaciente(){
        JPanel pnFrm = new PanelResultado();
        JPanel pnView = new ViewerResultado(entityManager);
        mantenimiento.CargarMantenimiento(pnView, pnFrm, true);
        mantenimiento.MandarSizePadre(0);   
        
        ((ViewerResultado)pnView).setResultadoSelected(resultado);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstudio;
    private javax.swing.JButton btnFragmento;
    private javax.swing.JButton btnPatologo;
    private javax.swing.JButton btnResultado;
    private javax.swing.JLabel imgEstudio;
    private javax.swing.JLabel imgFragmento;
    private javax.swing.JLabel imgResultado;
    private javax.swing.JLabel ingPatologo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblValorCodigo;
    // End of variables declaration//GEN-END:variables
}
