/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itla.apppatologia.vista.componentes;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import org.itla.apppatologia.vista.MainFrame;
import org.itla.apppatologia.vista.mantenimientos.IMantenimiento;
import org.itla.apppatologia.vista.mantenimientos.PanelARS;
import org.itla.apppatologia.vista.mantenimientos.PanelPaciente;
import org.itla.apppatologia.vista.viewers.IViewerObservable;
import org.itla.apppatologia.vista.viewers.ViewerARS;
import org.itla.apppatologia.vista.viewers.ViewerPaciente;

/**
 *
 * @author Chu
 */
public class PanelSubMenuPaciente extends javax.swing.JPanel implements ISubMenuObservable{
JPanel pnForm;
JPanel pnViewer;
private ArrayList<IPanelCentralObservador> observadores;
private IPanelCentralObservador observador;
private String nombre;
    /**
     * Creates new form PanelResultado
     */
    public PanelSubMenuPaciente() {
        initComponents();
        pnForm = null;
        pnViewer = null;
        observadores = new ArrayList<>();
        nombre = "paciente";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnPrincipal = new javax.swing.JPanel();
        pnSubMenuPaciente = new javax.swing.JPanel();
        tbSubMennuPaciente = new javax.swing.JToggleButton();
        pnSubMenuTipoPaciente = new javax.swing.JPanel();
        tbSubMenuTipoPaciente = new javax.swing.JToggleButton();
        pnSubMenuARS = new javax.swing.JPanel();
        tbSubMenuARS = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridLayout(0, 1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);

        pnPrincipal.setBackground(new java.awt.Color(240, 240, 240));
        pnPrincipal.setLayout(new java.awt.GridLayout(0, 1));

        pnSubMenuPaciente.setBackground(new java.awt.Color(240, 240, 240));
        pnSubMenuPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnSubMenuPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnSubMenuPacienteMouseEntered(evt);
            }
        });
        pnSubMenuPaciente.setLayout(new javax.swing.OverlayLayout(pnSubMenuPaciente));

        tbSubMennuPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        tbSubMennuPaciente.setText("<html>Paciente</html>");
        tbSubMennuPaciente.setContentAreaFilled(false);
        tbSubMennuPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbSubMennuPaciente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbSubMennuPaciente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbSubMennuPaciente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbSubMennuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSubMennuPacienteActionPerformed(evt);
            }
        });
        pnSubMenuPaciente.add(tbSubMennuPaciente);

        pnPrincipal.add(pnSubMenuPaciente);

        pnSubMenuTipoPaciente.setBackground(new java.awt.Color(240, 240, 240));
        pnSubMenuTipoPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnSubMenuTipoPacienteMouseClicked(evt);
            }
        });
        pnSubMenuTipoPaciente.setLayout(new javax.swing.OverlayLayout(pnSubMenuTipoPaciente));

        tbSubMenuTipoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        tbSubMenuTipoPaciente.setText("<html>Tipo Paciente</html>");
        tbSubMenuTipoPaciente.setContentAreaFilled(false);
        tbSubMenuTipoPaciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbSubMenuTipoPaciente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbSubMenuTipoPaciente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbSubMenuTipoPaciente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbSubMenuTipoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSubMenuTipoPacienteActionPerformed(evt);
            }
        });
        pnSubMenuTipoPaciente.add(tbSubMenuTipoPaciente);

        pnPrincipal.add(pnSubMenuTipoPaciente);

        pnSubMenuARS.setBackground(new java.awt.Color(240, 240, 240));
        pnSubMenuARS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnSubMenuARSMouseClicked(evt);
            }
        });
        pnSubMenuARS.setLayout(new javax.swing.OverlayLayout(pnSubMenuARS));

        tbSubMenuARS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3.png"))); // NOI18N
        tbSubMenuARS.setText("<html>ARS</html>");
        tbSubMenuARS.setContentAreaFilled(false);
        tbSubMenuARS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tbSubMenuARS.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbSubMenuARS.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbSubMenuARS.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/tool-3-seleccted.png"))); // NOI18N
        tbSubMenuARS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSubMenuARSActionPerformed(evt);
            }
        });
        pnSubMenuARS.add(tbSubMenuARS);

        pnPrincipal.add(pnSubMenuARS);

        jScrollPane1.setViewportView(pnPrincipal);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents
    
    public void Enlazar(IPanelCentralObservador o){
        observadores.add(o);
        observador = o;
    }
    
    private void tbSubMennuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSubMennuPacienteActionPerformed
        
        UnSelectAllButton();
        
        tbSubMennuPaciente.setSelected(true);
        pnSubMenuPaciente.setBackground(new Color(204,204,204));
        
        pnForm = new PanelPaciente();
        MainFrame padre = (MainFrame)observador;
        
        pnViewer = new ViewerPaciente(padre.getEntityManager());
        GetPanel(pnForm, pnViewer,false);
        
        IMantenimiento m = (IMantenimiento)pnForm;
        IViewerObservable v = (IViewerObservable)pnViewer;
        
        m.bind(v, observador);
        v.bind(m);
        observador.OcultarSubMenu();
        
        revalidate();
        repaint();
    }//GEN-LAST:event_tbSubMennuPacienteActionPerformed

    private void tbSubMenuTipoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSubMenuTipoPacienteActionPerformed
        UnSelectAllButton();
        tbSubMenuTipoPaciente.setSelected(true);
        pnSubMenuTipoPaciente.setBackground(new Color(204,204,204));
        
        observador.OcultarSubMenu();
    }//GEN-LAST:event_tbSubMenuTipoPacienteActionPerformed

    private void tbSubMenuARSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSubMenuARSActionPerformed
        UnSelectAllButton();
        tbSubMenuARS.setSelected(true);
        pnSubMenuARS.setBackground(new Color(204,204,204));
        pnForm = new PanelARS();
        
        MainFrame padre = (MainFrame)observador;
        
        pnViewer = new ViewerARS(padre.getEntityManager());
        GetPanel(pnForm,pnViewer,false);
        IMantenimiento m =(IMantenimiento)pnForm;
        IViewerObservable v = (IViewerObservable)pnViewer;
        m.bind(v,observador);
        v.bind(m);
        this.setPreferredSize(new Dimension(this.getPreferredSize().width+1, this.getPreferredSize().height));
        
        revalidate();
        repaint();
//        JFrame padre = (JFrame)observador;
//        padre.repaint();
//SwingUtilities.updateComponentTreeUI(padre);

    
        observador.OcultarSubMenu();

    }//GEN-LAST:event_tbSubMenuARSActionPerformed

    private void pnSubMenuPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSubMenuPacienteMouseClicked
        tbSubMennuPacienteActionPerformed(null);
    }//GEN-LAST:event_pnSubMenuPacienteMouseClicked

    private void pnSubMenuPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSubMenuPacienteMouseEntered
        
        
    }//GEN-LAST:event_pnSubMenuPacienteMouseEntered

    private void pnSubMenuTipoPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSubMenuTipoPacienteMouseClicked
        tbSubMenuTipoPacienteActionPerformed(null);
    }//GEN-LAST:event_pnSubMenuTipoPacienteMouseClicked

    private void pnSubMenuARSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSubMenuARSMouseClicked
        tbSubMenuARSActionPerformed(null);
    }//GEN-LAST:event_pnSubMenuARSMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JPanel pnSubMenuARS;
    private javax.swing.JPanel pnSubMenuPaciente;
    private javax.swing.JPanel pnSubMenuTipoPaciente;
    private javax.swing.JToggleButton tbSubMennuPaciente;
    private javax.swing.JToggleButton tbSubMenuARS;
    private javax.swing.JToggleButton tbSubMenuTipoPaciente;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Notificar() {
        for(IPanelCentralObservador ob: observadores){
            //ob.SetPanel(pnForm);
        }
    }

  

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    @Override
    public String getName() {
        return nombre;
    }

    @Override
    public void setName(String name) {
        super.setName(nombre); //To change body of generated methods, choose Tools | Templates.
    }
    

    @Override
    public void GetPanel(JPanel pnfrm,JPanel pnvwr, boolean sobreponer) {
        for(IPanelCentralObservador ob: observadores){
            ob.SetPanel(pnfrm,pnvwr,sobreponer);
        }
    }
    public void UnSelectAllButton(){
        JToggleButton jtb = new JToggleButton();
        for(Component c: pnPrincipal.getComponents()){
            if (c instanceof JPanel) {
                JPanel jp = new JPanel();
                jp = (JPanel)c;
                jp.setBackground(new Color(240,240,240));
                for(Component cc:jp.getComponents()){
                    if (cc instanceof JToggleButton) {
                        jtb = (JToggleButton)cc;
                        jtb.setSelected(false);
                    }
                }
            }
        }
    }
   
}
