/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.itla.apppatologia.vista.viewers;

import java.awt.Color;
import java.util.Collections;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.table.DefaultTableModel;
import org.itla.apppatologia.DTO.ArsDTO;
import org.itla.apppatologia.Repository.Aseguradora;
import org.itla.apppatologia.modelo.Contexto;
import org.itla.apppatologia.modelo.PersistenceUnits;
import org.itla.apppatologia.vista.mantenimientos.IMantenimiento;

/**
 *
 * @author Giame
 */
public class ViewerARS extends javax.swing.JPanel implements IViewerObservable{

    EntityManager entityManager;
    Contexto context;
    private List<Aseguradora> aseguradoras;
    private ArsDTO ars;
    //private JList<Aseguradora> lista = new JList<Aseguradora>();
    /**
     * Creates new form ViewerARS
     */
    IMantenimiento mantenimientoAsociado;
    public ViewerARS() {
        initComponents();
        
        
        
        context = new  Contexto();
        entityManager = context.getEntityManager(PersistenceUnits.getLocalContext());
        
        aseguradoras = entityManager.createNamedQuery("Aseguradora.findAll").getResultList();
        
        
        tablaAseguradoras.setModel(getModel(aseguradoras));
        
        RedisenarTabla();
        
        String txtCantidadPacientes = "<html>El"+"% de los pacientes están afiliados a esta aseguradora. Con un total de"+" pacienetes.</html>";
        String txtFechaPrimerPacientes = "<html>El primer paciente con esta aseguradora fue registrado el día</html>";
        String txtFechaUltimoPacientes = "<html>El ultimo paciente con esta aseguradora fue registrado el día</html>";
        jLabel9.setText(txtFechaPrimerPacientes);
        jLabel10.setText(txtFechaUltimoPacientes);
        jLabel6.setText(txtCantidadPacientes);
    }
    public ViewerARS(EntityManager em) {
        initComponents();
        
        
        entityManager=em;
//        context = new  Contexto();
//        entityManager = context.getEntityManager(PersistenceUnits.getLocalContext());
        
        aseguradoras = entityManager.createNamedQuery("Aseguradora.findAll").getResultList();
        
        
        tablaAseguradoras.setModel(getModel(aseguradoras));
        
        RedisenarTabla();
        
        String txtCantidadPacientes = "<html>El"+"% de los pacientes están afiliados a esta aseguradora. Con un total de"+" pacienetes.</html>";
        String txtFechaPrimerPacientes = "<html>El primer paciente con esta aseguradora fue registrado el día</html>";
        String txtFechaUltimoPacientes = "<html>El ultimo paciente con esta aseguradora fue registrado el día</html>";
        jLabel9.setText(txtFechaPrimerPacientes);
        jLabel10.setText(txtFechaUltimoPacientes);
        jLabel6.setText(txtCantidadPacientes);
    }

    @Override
    public String getName(){
        return "ars";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnListaPadre = new javax.swing.JPanel();
        pnBusqueda = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pnLista = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAseguradoras = new javax.swing.JTable();
        pnViewPadre = new javax.swing.JPanel();
        pnView = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblNombreARS = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnBotones = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        pnMenuSuperior = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 255));
        setLayout(new java.awt.BorderLayout());

        pnListaPadre.setPreferredSize(new java.awt.Dimension(254, 370));
        pnListaPadre.setLayout(new javax.swing.BoxLayout(pnListaPadre, javax.swing.BoxLayout.Y_AXIS));

        pnBusqueda.setPreferredSize(new java.awt.Dimension(110, 70));
        pnBusqueda.setLayout(new java.awt.GridLayout(2, 0));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/persistencia/lapiz.png"))); // NOI18N
        jButton6.setText("Editar");
        jPanel5.add(jButton6);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/persistencia/goma-de-borrar.png"))); // NOI18N
        jButton5.setText("Borrar");
        jPanel5.add(jButton5);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/persistencia/flechas-actualizar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);

        pnBusqueda.add(jPanel5);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jTextField1.setPreferredSize(new java.awt.Dimension(50, 28));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel4.add(jTextField1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/persistencia/busqueda.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        pnBusqueda.add(jPanel4);

        pnListaPadre.add(pnBusqueda);

        pnLista.setLayout(new java.awt.BorderLayout());

        tablaAseguradoras.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        tablaAseguradoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaAseguradoras.setRowHeight(30);
        tablaAseguradoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaAseguradorasMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAseguradoras);

        pnLista.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnListaPadre.add(pnLista);

        add(pnListaPadre, java.awt.BorderLayout.LINE_START);

        pnViewPadre.setBackground(new java.awt.Color(255, 255, 255));
        pnViewPadre.setBorder(null);
        pnViewPadre.setLayout(new java.awt.BorderLayout());

        pnView.setBackground(new java.awt.Color(255, 255, 255));
        pnView.setBorder(null);
        pnView.setForeground(new java.awt.Color(255, 255, 255));
        pnView.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 600));

        lblNombreARS.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblNombreARS.setText("nombre ARS");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/principales/ars.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        jLabel2.setText("Telefono:");

        jLabel3.setText("809-852-9654");

        jLabel4.setText("Dirección:");

        jLabel5.setText("Calle 32 No.84 Reparto, Santiago, Rep.Dom.");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/graficos/grafico-circular (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(35, 35, 35))
        );

        jLabel6.setText("Pacientes afiliados:");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel7.setText("Casos activos");

        jLabel8.setText("total de casos");

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel12.setText("Aseguradora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreARS)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(14, 14, 14)
                        .addComponent(lblNombreARS)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(57, 57, 57)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel2);

        pnView.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        pnViewPadre.add(pnView, java.awt.BorderLayout.CENTER);

        pnBotones.setLayout(new java.awt.BorderLayout());

        PanelMenu.setBackground(new java.awt.Color(255, 252, 236));
        PanelMenu.setBorder(null);
        PanelMenu.setPreferredSize(new java.awt.Dimension(70, 356));
        PanelMenu.setLayout(new java.awt.GridLayout(0, 1));

        pnMenuSuperior.setBackground(new java.awt.Color(255, 255, 255));
        pnMenuSuperior.setPreferredSize(new java.awt.Dimension(70, 170));
        pnMenuSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnMenuSuperiorMouseDragged(evt);
            }
        });
        pnMenuSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnMenuSuperiorMousePressed(evt);
            }
        });
        pnMenuSuperior.setLayout(new java.awt.GridLayout(3, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/persistencia/comprobado.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnMenuSuperior.add(jButton1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/persistencia/desenfrenado.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        pnMenuSuperior.add(jButton3);

        PanelMenu.add(pnMenuSuperior);

        jButton7.setBackground(new java.awt.Color(255, 237, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/itla/apppatologia/vista/PNG/botones/historial-medico (2).png"))); // NOI18N
        jButton7.setText("<html><p ALIGN=center>Reporte</p></html>");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton7);

        pnBotones.add(PanelMenu, java.awt.BorderLayout.LINE_START);

        pnViewPadre.add(pnBotones, java.awt.BorderLayout.LINE_END);

        add(pnViewPadre, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void pnMenuSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuSuperiorMouseDragged
//        Point point = MouseInfo.getPointerInfo().getLocation();
//
//        this.setLocation(point.x-x,point.y-y);
    }//GEN-LAST:event_pnMenuSuperiorMouseDragged

    private void pnMenuSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuSuperiorMousePressed
//        x = evt.getX();
//        y = evt.getY();
    }//GEN-LAST:event_pnMenuSuperiorMousePressed

    private void tablaAseguradorasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAseguradorasMousePressed
        tablaAseguradoras.setSelectionBackground(Color.PINK);
        tablaAseguradoras.setSelectionForeground(Color.white);
        ars = new ArsDTO();
        ars.setId((Integer)tablaAseguradoras.getModel().getValueAt(tablaAseguradoras.getSelectedRow(), 0));
        ars.setNombre((String)tablaAseguradoras.getModel().getValueAt(tablaAseguradoras.getSelectedRow(), 1));
        ars.setTelefono((String)tablaAseguradoras.getModel().getValueAt(tablaAseguradoras.getSelectedRow(), 2));
        ars.setDirecion((String)tablaAseguradoras.getModel().getValueAt(tablaAseguradoras.getSelectedRow(), 3));
        
        lblNombreARS.setText(ars.getNombre());
        
        jLabel3.setText(ars.getTelefono());
        jLabel5.setText(ars.getDirecion());
        
        mantenimientoAsociado.Show((Object)ars);
    }//GEN-LAST:event_tablaAseguradorasMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ars = (ArsDTO)mantenimientoAsociado.Save();
//        if (ars.getId()>0) {
//            tablaAseguradoras.getModel().setValueAt(ars.getNombre(), tablaAseguradoras.getSelectedRow(), 1);
//        }
        aseguradoras = entityManager.createNamedQuery("Aseguradora.findAll").getResultList();
        tablaAseguradoras.setModel(getModel(aseguradoras));
        RedisenarTabla();
//        tablaAseguradoras.getModel().setValueAt(, WIDTH, WIDTH);getValueAt(tablaAseguradoras.getSelectedRow(), 1);
//        List<Aseguradora> newAseguradoras;
//        newAseguradoras = entityManager.createNamedQuery("Aseguradora.findAll").getResultList();
//        tablaAseguradoras.setModel(getModel(newAseguradoras));
//        RedisenarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        DefaultTableModel model = (DefaultTableModel) tablaAseguradoras.getModel();
        DefaultTableModel newModel = new DefaultTableModel();
        
        Object[] registro = new Object[4];
        
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 1).toString().contains(jTextField1.getText().subSequence(0, 1))) {
                registro[0] = model.getValueAt(i, 0);
                registro[1] = model.getValueAt(i, 1);
                registro[2] = model.getValueAt(i, 2);
                registro[3] = model.getValueAt(i, 3);
                
                newModel.addRow(registro);
            }
            
        }
        tablaAseguradoras.setModel(newModel);
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       aseguradoras = entityManager.createNamedQuery("Aseguradora.findAll").getResultList();
        
        tablaAseguradoras.setModel(getModel(aseguradoras));
        
        RedisenarTabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
    }//GEN-LAST:event_jButton7ActionPerformed

    @Override
    public void bind(IMantenimiento m) {
         mantenimientoAsociado = m;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblNombreARS;
    private javax.swing.JPanel pnBotones;
    private javax.swing.JPanel pnBusqueda;
    private javax.swing.JPanel pnLista;
    private javax.swing.JPanel pnListaPadre;
    private javax.swing.JPanel pnMenuSuperior;
    private javax.swing.JPanel pnView;
    private javax.swing.JPanel pnViewPadre;
    private javax.swing.JTable tablaAseguradoras;
    // End of variables declaration//GEN-END:variables

    @Override//metodo de la interface que manda al panel formulario
    public void mandar(String txt) {
       // jLabel1.setText(txt);
    }
    public DefaultTableModel getModel(List<Aseguradora> lista){
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Id");        
        modelo.addColumn("Nombre");       
        modelo.addColumn("Telefono");     
        modelo.addColumn("Direccion");

        Object[] registro = new Object[4];
        
        Collections.reverse(lista);
        for(Aseguradora ars: lista){
               
                    registro[0] = ars.getIdaseguradora();
                    registro[1] = ars.getNombre();
                    registro[2] = ars.getTelefono();
                    registro[3] = ars.getDireccion();
          
                modelo.addRow(registro);
               
            } 
        
        return modelo;
    }
    
    public void RedisenarTabla(){
        tablaAseguradoras.setTableHeader(null);
        tablaAseguradoras.removeColumn(tablaAseguradoras.getColumnModel().getColumn(0));
        tablaAseguradoras.removeColumn(tablaAseguradoras.getColumnModel().getColumn(2));
        tablaAseguradoras.removeColumn(tablaAseguradoras.getColumnModel().getColumn(1));
    }

    @Override
    public void Buscar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void PasarACampos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
